name: openvla
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - debugpy=1.6.0
  - decorator=5.2.1
  - entrypoints=0.4
  - executing=2.2.0
  - ipykernel=6.20.2
  - ipython=8.36.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=23.0.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - aiofiles==23.2.1
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - array-record==0.6.0
      - astunparse==1.6.3
      - attrs==24.3.0
      - bddl==3.5.0
      - bitsandbytes==0.45.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.31.4
      - contourpy==1.3.1
      - crcmod==1.7
      - cryptography==44.0.3
      - cycler==0.12.1
      - decord==0.6.0
      - distlib==0.3.9
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - easydict==1.13
      - egl-probe==1.0.2
      - einops==0.8.0
      - etils==1.12.0
      - exceptiongroup==1.2.2
      - fairscale==0.4.13
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - ffmpeg-python==0.2.0
      - ffmpy==0.5.0
      - filelock==3.13.1
      - flash-attn==2.7.3
      - flatbuffers==25.2.10
      - fonttools==4.55.3
      - fsspec==2024.2.0
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.8.0
      - google-pasta==0.2.0
      - gradio==4.19.0
      - gradio-client==0.10.0
      - grpcio==1.69.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - hydra-core==1.3.2
      - identify==2.6.5
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - jinja2==3.1.3
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupytext==1.16.7
      - keras==3.8.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - llvmlite==0.44.0
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - mujoco==3.2.7
      - namex==0.0.8
      - narwhals==1.21.1
      - nbformat==5.10.4
      - networkx==3.2.1
      - ninja==1.11.1.3
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numba==0.61.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.0
      - orjson==3.10.14
      - oss2==2.19.1
      - packaging==24.2
      - pandas==2.2.3
      - pathlib==1.0.1
      - peft==0.14.0
      - pillow==10.2.0
      - piqa==1.3.2
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.0.1
      - promise==2.3
      - protobuf==3.20.3
      - psutil==6.1.1
      - pyarrow==19.0.0
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyopengl==3.1.9
      - pyparsing==3.2.1
      - pytest==8.3.4
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.35.1
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - robomimic==0.3.0
      - robosuite==1.4.0
      - rpds-py==0.22.3
      - ruff==0.9.1
      - safetensors==0.5.2
      - scipy==1.15.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.21.0
      - setproctitle==1.3.4
      - shellingham==1.5.4
      - simple-parsing==0.1.7
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - starlette==0.41.3
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.18.0
      - tensorflow-datasets==4.9.7
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.16.1
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.5.0+cu124
      - torchaudio==2.5.0+cu124
      - torchvision==0.20.0+cu124
      - tqdm==4.67.1
      - transformers==4.48.0
      - triton==3.1.0
      - typer==0.15.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - virtualenv==20.28.1
      - wandb==0.19.6
      - websockets==11.0.3
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zipp==3.21.0